# Generated by Django 5.1.3 on 2024-12-11 09:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    replaces = [('public_profile', '0001_initial'), ('public_profile', '0002_alter_profile_user'), ('public_profile', '0003_alter_profile_user'), ('public_profile', '0004_delete_profile')]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
    ]
