# Generated by Django 5.1.3 on 2024-12-11 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public_profile', '0003_alter_profile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
