# Generated by Django 5.1.3 on 2024-12-11 09:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    replaces = [('post', '0006_profile'), ('post', '0007_rename_username_profile_user'), ('post', '0008_delete_profile')]

    dependencies = [
        ('post', '0005_alter_comment_body'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
    ]
