# Generated by Django 5.1.3 on 2024-12-10 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='username',
            new_name='user',
        ),
    ]
