# Generated by Django 5.1.3 on 2024-12-12 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_profile_squashed_0008_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageTags',
            fields=[
                ('tag_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ImageTagRelationships',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_id', to='post.post')),
                ('tag_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_tag', to='post.imagetags')),
            ],
        ),
    ]
