# Generated by Django 5.1.3 on 2024-12-12 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_imagetags_imagetagrelationships'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagetags',
            name='tag_name',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
