# Generated by Django 5.1.3 on 2024-12-12 11:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_alter_imagetags_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagetags',
            name='tag_name',
            field=models.CharField(max_length=200, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(code='invalid_tag_name', message='Tag name must contain only letters, digits, spaces, and hyphens.', regex='^[a-zA-Z0-9 \\-]+$')]),
        ),
    ]
