# Generated by Django 5.1.3 on 2025-01-16 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0017_post_liked_by_alter_comment_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(blank=True, max_length=600),
        ),
    ]
