# Generated by Django 5.1.3 on 2025-01-29 15:18

import cloudinary.models
import django.core.validators
import post.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0023_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), post.models.validate_image_size], verbose_name='image'),
        ),
    ]
