# Generated by Django 5.1.3 on 2024-12-23 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0014_alter_post_image'),
        ('profile_page', '0003_imageboard_boardimagerelationship'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='boardimagerelationship',
            unique_together={('post_id', 'board_id')},
        ),
    ]
