# Generated by Django 5.1.3 on 2025-01-08 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0004_alter_boardimagerelationship_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageboard',
            name='visablility',
            field=models.IntegerField(choices=[(0, 'Public'), (1, 'Private')], default=0),
        ),
    ]
