# Generated by Django 5.1.3 on 2025-01-08 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0005_imageboard_visablility'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imageboard',
            old_name='visablility',
            new_name='visiblility',
        ),
    ]
