# Generated by Django 5.1.3 on 2025-01-08 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0006_rename_visablility_imageboard_visiblility'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imageboard',
            old_name='visiblility',
            new_name='visibility',
        ),
    ]
