# Generated by Django 5.1.3 on 2025-01-16 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0013_alter_profile_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageboard',
            name='title',
            field=models.CharField(max_length=90),
        ),
    ]
