# Generated by Django 5.1.3 on 2025-02-09 13:44

import cloudinary.models
import django.core.validators
import post.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0015_alter_profile_first_name_alter_profile_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/dygztovba/image/upload/v1736352521/wmj7j0gxfg9rch8chlfl.jpg', max_length=255, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), post.models.validate_image_size], verbose_name='image'),
        ),
    ]
