# Generated by Django 5.1.3 on 2025-02-16 12:47

import cloudinary.models
import profile_page.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0016_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/dygztovba/image/upload/v1736352521/wmj7j0gxfg9rch8chlfl.jpg', max_length=255, validators=[profile_page.models.validate_image], verbose_name='image'),
        ),
    ]
